# Generated by Django 2.0.5 on 2018-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark', # 테이블명
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # 기본 ID 생성
                ('site_name', models.CharField(max_length=100)), # site_name 필드
                ('url', models.URLField(verbose_name='url')), # url 필드
            ],
            options={
                'ordering': ['site_name'],
            },
        ),
    ]
